# Generated by Django 6.0.3 on 2026-04-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='employee',
        ),
    ]
