# Generated by Django 6.0.3 on 2026-04-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_role_user_ismanager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='e_first_name',
            new_name='e_firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='e_last_name',
            new_name='e_lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isManager',
            new_name='is_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='e_password',
        ),
    ]
