# Generated by Django 6.0.3 on 2026-04-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_e_first_name_user_e_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('camera_id', models.CharField(max_length=100)),
                ('employee_name', models.CharField(blank=True, default='', max_length=255)),
                ('trigger_reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
